describe('Task - Tray.io', function() {
  it('Test', function() {
    cy.readFile('./cypress/fixtures/data.json').then((json) => {
      cy.viewport('macbook-11')
      cy.visit('https://tray.io/')
      cy.get('a[href="https://app.tray.io"]').click()
      cy.url().should('contain', 'login')
      cy.get('input[name="username"]').type(json.email)
      cy.get('input[name="password"]').type(json.pass)
      cy.get('button').click()
      cy.get('a[href="/create"]').click()
      cy.get('input[name="name"]').type('new-workflow')
      cy.get('div[title="Create"]').click()
      cy.wait(10000)
      cy.get('div.Connector-List___IwWg5K > div:nth-child(1) > div').click()
      cy.get('div.Toolbar___2ftREM.Header___JAfaaT > div.Header-buttons___C1wwvK > a.has-icon___2urrTn.danger___2Wv8VA').click({multiple: true, force: true})
      cy.get('div[class^="Options-menu"]').trigger('mouseover')
      cy.get('div.List___xucddv > ul > li.FilterableListItem.FilterableFlowListItem___iatfeO.Disabled___1Xh4lH > div > div > ul > li:nth-child(5) > a').click({force: true})
      cy.get('div.Dialog-footer-button___31Yis7.button___1PSJhJ.success___3Tf3_d.uppercase___2hcvEE').click({force: true})
      cy.wait(2000)
      cy.get('i#userToggle').click()
      cy.get('div.Page-navigation-container___3wppHF > div > div:nth-child(2) > ul > li:nth-child(2) > a').click()
    })
  })
})
